[package]
name = "rbpf-cli"
version = "1.10.15"
description = "CLI to test and analyze eBPF programs"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/rbpf"
homepage = "https://solana.com/"
keywords = ["BPF", "eBPF", "interpreter", "JIT"]
edition = "2021"
publish = false

[dependencies]
bv = "0.11.1"
clap = { version = "3.1.5", features = ["cargo"] }
gimli = "0.26.1"
goblin = { version = "0.5.1", features = ["std"] }
itertools = "0.10.3"
log = { version = "0.4.14", features = ["std"] }
serde = "1.0.136"
serde_json = "1.0.79"
solana-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.10.15" }
solana-logger = { path = "../logger", version = "=1.10.15" }
solana-program-runtime = { path = "../program-runtime", version = "=1.10.15" }
solana-sdk = { path = "../sdk", version = "=1.10.15" }
solana_rbpf = "=0.2.24"
