[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-store-tool"
description = "Tool to inspect append vecs"
version = "1.10.8"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
clap = "2.33.1"
log = { version = "0.4.14" }
solana-logger = { path = "../../logger", version = "=1.10.8" }
solana-runtime = { path = "..", version = "=1.10.8" }
solana-version = { path = "../../version", version = "=1.10.8" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
